name: Java Unit Tests

on:
  push:
    branches:
      - main  # Specify the branch to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest  # The runner environment for your workflow

    steps:
      - name: Checkout Code into the Environment
        uses: actions/checkout@v2  # This action checks out your code from the repository

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'  # Specify the distribution (e.g., 'adopt', 'adopt-openj9', 'corretto', etc.)

      - name: Build with Maven
        run: mvn clean install  # Adjust the build command if you use a different build tool

      - name: Run Unit Tests
        run: mvn test  # Adjust the test command if needed
