name: Java Unit Tests

on:
  push:
    branches:
      - main  # Specify the branch to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest  # The runner environment for your workflow

    steps:
      - name: Checkout Code into the Environment
        uses: actions/checkout@v2  # This action checks out your code from the repository

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build project with Maven
        run: mvn -B package --file pom.xml

      - name: Run Unit Tests
        run: mvn test  # Adjust the test command if needed
